from app.models.strategy import StrategyDefinition


EASYLANGUAGE_TEMPLATE = """{{ Generated by Market Intelligence Hub v19 Refactor }}
{{ Strategy: {name} }}
{{ Direction: {direction} }}
{{ Timeframe: {timeframe} }}

Inputs:
    FastEMALen(29),
    SlowEMALen(54),
    ADXLen(14),
    ADXMin(16),
    RVOLLen(20),
    RVOLMin(1.5);

Vars:
    EMAFast(0),
    EMASlow(0),
    ADXValue(0),
    RVOL(0),
    TrendLong(False),
    TrendShort(False),
    MomentumOK(False),
    VolumeOK(False),
    PullbackLong(False),
    PullbackShort(False);

EMAFast = XAverage(Close, FastEMALen);
EMASlow = XAverage(Close, SlowEMALen);
ADXValue = ADX(ADXLen);
RVOL = Volume / Average(Volume, RVOLLen);

TrendLong = EMAFast > EMASlow;
TrendShort = EMAFast < EMASlow;
MomentumOK = ADXValue > ADXMin;
VolumeOK = RVOL > RVOLMin;

PullbackLong = Low <= EMAFast and Close > EMAFast and Close > Open;
PullbackShort = High >= EMAFast and Close < EMAFast and Close < Open;

If TrendLong and MomentumOK and VolumeOK and PullbackLong Then
    Buy ("VSB Long") Next Bar at Market;

If MarketPosition = 1 and Close < EMASlow Then
    Sell ("VSB LX") Next Bar at Market;

If "{direction}" <> "Long Only" and TrendShort and MomentumOK and VolumeOK and PullbackShort Then
    SellShort ("VSB Short") Next Bar at Market;

If MarketPosition = -1 and Close > EMASlow Then
    BuyToCover ("VSB SX") Next Bar at Market;
"""


def generate_easylanguage(strategy: StrategyDefinition) -> str:
    return EASYLANGUAGE_TEMPLATE.format(
        name=strategy.name,
        direction=strategy.direction,
        timeframe=strategy.timeframe,
    )
