from app.models.strategy import StrategyDefinition


PINE_TEMPLATE = """//@version=6
strategy("{name}", overlay=true, initial_capital=10000, pyramiding=0, process_orders_on_close=true)

// Generated by Market Intelligence Hub v19 Refactor
// Direction: {direction}
// Timeframe intent: {timeframe}
// Trend: {trend_filter}
// Momentum: {momentum_filter}
// Volume: {volume_filter}
// Entry: {entry_rule}
// Exit: {exit_rule}
// Risk: {risk_rule}

emaFastLen = input.int(29, "Fast EMA")
emaSlowLen = input.int(54, "Slow EMA")
adxLen = input.int(14, "ADX Length")
adxMin = input.float(16, "ADX Minimum")
rvolLen = input.int(20, "RVOL Length")
rvolMin = input.float(1.5, "RVOL Minimum")

emaFast = ta.ema(close, emaFastLen)
emaSlow = ta.ema(close, emaSlowLen)
[diPlus, diMinus, adx] = ta.dmi(adxLen, adxLen)
rvol = volume / ta.sma(volume, rvolLen)

trendLong = emaFast > emaSlow
trendShort = emaFast < emaSlow
momentumOK = adx > adxMin
volumeOK = rvol > rvolMin

pullbackLong = low <= emaFast and close > emaFast and close > open
pullbackShort = high >= emaFast and close < emaFast and close < open

longSignal = trendLong and momentumOK and volumeOK and pullbackLong
shortSignal = trendShort and momentumOK and volumeOK and pullbackShort

if longSignal
    strategy.entry("Long", strategy.long)

if {allow_short} and shortSignal
    strategy.entry("Short", strategy.short)

if strategy.position_size > 0 and close < emaSlow
    strategy.close("Long")

if strategy.position_size < 0 and close > emaSlow
    strategy.close("Short")

plot(emaFast, "EMA Fast", color=color.yellow)
plot(emaSlow, "EMA Slow", color=color.aqua)

alertcondition(longSignal, "Long Signal", "Visual Strategy Builder long signal")
alertcondition(shortSignal, "Short Signal", "Visual Strategy Builder short signal")
"""


def generate_pine(strategy: StrategyDefinition) -> str:
    return PINE_TEMPLATE.format(
        name=strategy.name.replace('"', "'"),
        direction=strategy.direction,
        timeframe=strategy.timeframe,
        trend_filter=strategy.trend_filter,
        momentum_filter=strategy.momentum_filter,
        volume_filter=strategy.volume_filter,
        entry_rule=strategy.entry_rule,
        exit_rule=strategy.exit_rule,
        risk_rule=strategy.risk_rule,
        allow_short=str("Long Only" not in strategy.direction).lower(),
    )
