from app.models.strategy import StrategyDefinition


PYTHON_TEMPLATE = """\"\"\"
Generated by Market Intelligence Hub v19 Refactor
Strategy: {name}
Direction: {direction}
Timeframe: {timeframe}
\"\"\"

import pandas as pd


def ema(series: pd.Series, length: int) -> pd.Series:
    return series.ewm(span=length, adjust=False).mean()


def build_signals(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["ema_fast"] = ema(df["close"], 29)
    df["ema_slow"] = ema(df["close"], 54)
    df["rvol"] = df["volume"] / df["volume"].rolling(20).mean()

    if "adx" not in df.columns:
        df["adx"] = 20

    df["trend_long"] = df["ema_fast"] > df["ema_slow"]
    df["trend_short"] = df["ema_fast"] < df["ema_slow"]
    df["momentum_ok"] = df["adx"] > 16
    df["volume_ok"] = df["rvol"] > 1.5

    df["pullback_long"] = (
        (df["low"] <= df["ema_fast"]) &
        (df["close"] > df["ema_fast"]) &
        (df["close"] > df["open"])
    )

    df["pullback_short"] = (
        (df["high"] >= df["ema_fast"]) &
        (df["close"] < df["ema_fast"]) &
        (df["close"] < df["open"])
    )

    df["long_signal"] = (
        df["trend_long"] &
        df["momentum_ok"] &
        df["volume_ok"] &
        df["pullback_long"]
    )

    df["short_signal"] = (
        df["trend_short"] &
        df["momentum_ok"] &
        df["volume_ok"] &
        df["pullback_short"]
    )

    df["exit_long"] = df["close"] < df["ema_slow"]
    df["exit_short"] = df["close"] > df["ema_slow"]

    return df
"""


def generate_python(strategy: StrategyDefinition) -> str:
    return PYTHON_TEMPLATE.format(
        name=strategy.name,
        direction=strategy.direction,
        timeframe=strategy.timeframe,
    )
